# Generated by Django 5.2.13 on 2026-05-04 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(max_length=64, unique=True)),
                ('nickname', models.CharField(blank=True, max_length=200)),
                ('carrier', models.CharField(default='fedex', max_length=50)),
                ('status', models.CharField(blank=True, max_length=200)),
                ('status_code', models.CharField(blank=True, max_length=100)),
                ('latest_event_at', models.DateTimeField(blank=True, null=True)),
                ('latest_location', models.CharField(blank=True, max_length=255)),
                ('estimated_delivery', models.CharField(blank=True, max_length=255)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('has_exception', models.BooleanField(default=False)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('last_alert_fingerprint', models.CharField(blank=True, max_length=255)),
                ('last_raw_payload', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PackageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=200)),
                ('status_code', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('details', models.TextField(blank=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='tracker.package')),
            ],
            options={
                'ordering': ['-event_time', '-created_at'],
            },
        ),
    ]
