# Generated by Django 5.2.13 on 2026-05-04 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_savedreference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='tracking_number',
            field=models.CharField(db_index=True, max_length=64, unique=True),
        ),
    ]
